### ISSUE TITLE
Added auto generated exe files for new pushes on main

### ISSUE THREAD

**Issue by Pramell94** [OskarSundberg/TMUKGroup3#92]
```
    - name: Upload assets
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./program.tar.gz
        asset_name: program-${{ runner.os }}.tar.gz
        asset_content_type: application/tar.gz
```
